[package]
name = "vulcan-sync"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
blake3.workspace = true
fs2.workspace = true
globset.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tempfile.workspace = true
ulid.workspace = true
unicode-normalization.workspace = true

[dev-dependencies]

[lints]
workspace = true
