[package]
name = "vulcan-daemon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
web = ["vulcan-app/web"]

[dependencies]
axum.workspace = true
fs2.workspace = true
base64.workspace = true
getrandom.workspace = true
notify.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
subtle.workspace = true
tempfile.workspace = true
tokio.workspace = true
toml.workspace = true
tower.workspace = true
ulid.workspace = true
vulcan-app = { path = "../vulcan-app", version = "0.1.0", default-features = false }
vulcan-core = { path = "../vulcan-core", version = "0.1.0", default-features = false }
vulcan-sync = { path = "../vulcan-sync", version = "0.1.0" }

[lints]
workspace = true
