
# Dynamic completions patch — generated by vulcan completions bash
__vulcan_completion_prefix_args() {
    local -a args=()
    local i=1
    while (( i < ${#COMP_WORDS[@]} )); do
        local word="${COMP_WORDS[i]}"
        case "$word" in
            --vault|--output|--refresh|--fields|--provider|--permissions|--limit|--offset|--color)
                args+=("$word")
                if (( i + 1 < ${#COMP_WORDS[@]} )); then
                    args+=("${COMP_WORDS[i + 1]}")
                fi
                ((i += 2))
                ;;
            --vault=*|--output=*|--refresh=*|--fields=*|--provider=*|--permissions=*|--limit=*|--offset=*|--color=*)
                args+=("$word")
                ((i += 1))
                ;;
            --verbose|--quiet|-q|--no-header)
                args+=("$word")
                ((i += 1))
                ;;
            --)
                break
                ;;
            -*)
                break
                ;;
            *)
                break
                ;;
        esac
    done
    printf '%s\n' "${args[@]}"
}

__vulcan_dynamic_complete() {
    local context="$1"
    local cmd="__VULCAN_CMD__"
    local arg candidate
    local -a args=()
    COMPREPLY=()
    while IFS= read -r arg; do
        args+=("$arg")
    done < <(__vulcan_completion_prefix_args)
    while IFS= read -r candidate; do
        COMPREPLY+=("$candidate")
    done < <("$cmd" "${args[@]}" complete "$context" "${COMP_WORDS[COMP_CWORD]}" 2>/dev/null)
    return 0
}

__vulcan_dynamic_candidates() {
    local context="$1"
    local prefix="$2"
    local cmd="__VULCAN_CMD__"
    local arg candidate
    local -a args=()
    while IFS= read -r arg; do
        args+=("$arg")
    done < <(__vulcan_completion_prefix_args)
    while IFS= read -r candidate; do
        printf '%s\n' "$candidate"
    done < <("$cmd" "${args[@]}" complete "$context" "$prefix" 2>/dev/null)
}

__vulcan_tool_run_name() {
    local i j word
    for (( i = 1; i < COMP_CWORD; i++ )); do
        if [[ "${COMP_WORDS[i]}" == "tool" && "${COMP_WORDS[i + 1]}" == "run" ]]; then
            j=$((i + 2))
            while (( j < COMP_CWORD )); do
                word="${COMP_WORDS[j]}"
                case "$word" in
                    --input-json|--input-file)
                        ((j += 2))
                        ;;
                    --*)
                        ((j += 1))
                        ;;
                    *)
                        printf '%s\n' "$word"
                        return 0
                        ;;
                esac
            done
        fi
    done
}

__vulcan_is_tool_run_context() {
    local i
    for (( i = 1; i < COMP_CWORD; i++ )); do
        if [[ "${COMP_WORDS[i]}" == "tool" && "${COMP_WORDS[i + 1]}" == "run" ]]; then
            return 0
        fi
    done
    return 1
}

__vulcan_is_tool_name_context() {
    local i command
    for (( i = 1; i < COMP_CWORD; i++ )); do
        if [[ "${COMP_WORDS[i]}" == "tool" ]]; then
            command="${COMP_WORDS[i + 1]}"
            if [[ "$command" =~ ^(show|help|test|compat|types)$ ]]; then
                return 0
            fi
        fi
    done
    return 1
}

__vulcan_append_completion_candidate() {
    local candidate existing
    candidate="$1"
    for existing in "${COMPREPLY[@]}"; do
        if [[ "$existing" == "$candidate" ]]; then
            return
        fi
    done
    COMPREPLY+=("$candidate")
}

__vulcan_dynamic_dispatch() {
    _vulcan "$@"
    if __vulcan_is_tool_run_context; then
        local tool candidate
        tool="$(__vulcan_tool_run_name)"
        if [[ -z "$tool" && "${cur:-${COMP_WORDS[COMP_CWORD]}}" != -* ]]; then
            COMPREPLY=()
            while IFS= read -r candidate; do
                __vulcan_append_completion_candidate "$candidate"
            done < <(__vulcan_dynamic_candidates custom-tool "${COMP_WORDS[COMP_CWORD]}")
        elif [[ -n "$tool" && "${cur:-${COMP_WORDS[COMP_CWORD]}}" == --* ]]; then
            while IFS= read -r candidate; do
                __vulcan_append_completion_candidate "$candidate"
            done < <(__vulcan_dynamic_candidates "custom-tool-flag:$tool" "${COMP_WORDS[COMP_CWORD]}")
        elif [[ -n "$tool" && "${COMP_WORDS[COMP_CWORD - 1]}" == --* ]]; then
            COMPREPLY=()
            local flag="${COMP_WORDS[COMP_CWORD - 1]#--}"
            while IFS= read -r candidate; do
                __vulcan_append_completion_candidate "$candidate"
            done < <(__vulcan_dynamic_candidates "custom-tool-value:$tool:$flag" "${COMP_WORDS[COMP_CWORD]}")
        fi
    elif __vulcan_is_tool_name_context && [[ "${cur:-${COMP_WORDS[COMP_CWORD]}}" != -* ]]; then
        COMPREPLY=()
        local candidate
        while IFS= read -r candidate; do
            __vulcan_append_completion_candidate "$candidate"
        done < <(__vulcan_dynamic_candidates custom-tool "${COMP_WORDS[COMP_CWORD]}")
    fi
}

if [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -ge 4 || "${BASH_VERSINFO[0]}" -gt 4 ]]; then
    complete -F __vulcan_dynamic_dispatch -o nosort -o bashdefault -o default vulcan
else
    complete -F __vulcan_dynamic_dispatch -o bashdefault -o default vulcan
fi

# Override completion for specific subcommand contexts
_vulcan_complete_note_arg() {
    if [[ "${COMP_WORDS[1]}" == "note" || "${COMP_WORDS[1]}" == "links" || "${COMP_WORDS[1]}" == "backlinks" ]]; then
        __vulcan_dynamic_complete note
    fi
}

_vulcan_complete_kanban_arg() {
    if [[ "${COMP_WORDS[1]}" == "kanban" ]]; then
        __vulcan_dynamic_complete kanban-board
    fi
}

_vulcan_complete_bases_arg() {
    if [[ "${COMP_WORDS[1]}" == "bases" ]] && [[ "${COMP_WORDS[2]}" =~ ^(eval|tui|create|view-add|view-delete|view-rename)$ ]]; then
        __vulcan_dynamic_complete bases-file
    fi
}
