
# Dynamic completions patch — generated by vulcan completions bash
__vulcan_completion_prefix_args() {
    local -a args=()
    local i=1
    while (( i < ${#COMP_WORDS[@]} )); do
        local word="${COMP_WORDS[i]}"
        case "$word" in
            --vault|--output|--refresh|--fields|--provider|--permissions|--limit|--offset|--color)
                args+=("$word")
                if (( i + 1 < ${#COMP_WORDS[@]} )); then
                    args+=("${COMP_WORDS[i + 1]}")
                fi
                ((i += 2))
                ;;
            --vault=*|--output=*|--refresh=*|--fields=*|--provider=*|--permissions=*|--limit=*|--offset=*|--color=*)
                args+=("$word")
                ((i += 1))
                ;;
            --verbose|--quiet|-q|--no-header)
                args+=("$word")
                ((i += 1))
                ;;
            --)
                break
                ;;
            -*)
                break
                ;;
            *)
                break
                ;;
        esac
    done
    printf '%s\n' "${args[@]}"
}

__vulcan_dynamic_complete() {
    local context="$1"
    local cmd="__VULCAN_CMD__"
    local arg candidate
    local -a args=()
    COMPREPLY=()
    while IFS= read -r arg; do
        args+=("$arg")
    done < <(__vulcan_completion_prefix_args)
    while IFS= read -r candidate; do
        COMPREPLY+=("$candidate")
    done < <("$cmd" "${args[@]}" complete "$context" "${COMP_WORDS[COMP_CWORD]}" 2>/dev/null)
    return 0
}

__vulcan_dynamic_candidates() {
    local context="$1"
    local prefix="$2"
    local cmd="__VULCAN_CMD__"
    local arg candidate
    local -a args=()
    while IFS= read -r arg; do
        args+=("$arg")
    done < <(__vulcan_completion_prefix_args)
    while IFS= read -r candidate; do
        printf '%s\n' "$candidate"
    done < <("$cmd" "${args[@]}" complete "$context" "$prefix" 2>/dev/null)
}

__vulcan_tool_run_name() {
    local i j word
    for (( i = 1; i < COMP_CWORD; i++ )); do
        if [[ "${COMP_WORDS[i]}" == "tool" && "${COMP_WORDS[i + 1]}" == "run" ]]; then
            j=$((i + 2))
            while (( j < COMP_CWORD )); do
                word="${COMP_WORDS[j]}"
                case "$word" in
                    --input-json|--input-file)
                        ((j += 2))
                        ;;
                    --*)
                        ((j += 1))
                        ;;
                    *)
                        printf '%s\n' "$word"
                        return 0
                        ;;
                esac
            done
        fi
    done
}

__vulcan_is_tool_run_context() {
    local i
    for (( i = 1; i < COMP_CWORD; i++ )); do
        if [[ "${COMP_WORDS[i]}" == "tool" && "${COMP_WORDS[i + 1]}" == "run" ]]; then
            return 0
        fi
    done
    return 1
}

__vulcan_is_tool_name_context() {
    local i command
    for (( i = 1; i < COMP_CWORD; i++ )); do
        if [[ "${COMP_WORDS[i]}" == "tool" ]]; then
            command="${COMP_WORDS[i + 1]}"
            if [[ "$command" =~ ^(show|help|test|compat|types)$ ]]; then
                return 0
            fi
        fi
    done
    return 1
}

__vulcan_append_completion_candidate() {
    local candidate existing index existing_count
    candidate="$1"
    if ! declare -p COMPREPLY >/dev/null 2>&1; then
        COMPREPLY=()
    fi
    existing_count=${#COMPREPLY[@]}
    for (( index = 0; index < existing_count; index++ )); do
        existing="${COMPREPLY[index]}"
        if [[ "$existing" == "$candidate" ]]; then
            return
        fi
    done
    COMPREPLY+=("$candidate")
}

__vulcan_named_completion_context() {
    local previous="${COMP_WORDS[COMP_CWORD - 1]}"
    local joined=" ${COMP_WORDS[*]:0:COMP_CWORD} "
    case "$previous" in
        --permissions|--clone|--permission-profile)
            printf '%s\n' permission-profile
            return
            ;;
        --site-profile)
            printf '%s\n' site-profile
            return
            ;;
        --profile)
            if [[ "$joined" == *" export outline-zip "* ]]; then
                printf '%s\n' outline-profile
            elif [[ "$joined" == *" site "* ]]; then
                printf '%s\n' site-profile
            elif [[ "$joined" == *" tool "* ]]; then
                printf '%s\n' permission-profile
            fi
            return
            ;;
    esac

    if [[ "$previous" == outline && "$joined" =~ \ (publish|pull)\ outline\ $ ]]; then
        printf '%s\n' outline-profile
    elif [[ "$joined" == *" outline collections "* && "$previous" =~ ^(list|show|create|update|archive|restore|bind)$ ]]; then
        printf '%s\n' outline-profile
    elif [[ "$joined" == *" export profile rule "* && "$previous" =~ ^(list|add|update|delete|move)$ ]]; then
        printf '%s\n' export-profile
    elif [[ "$joined" == *" export profile "* && "$previous" =~ ^(run|serve|show|set|delete)$ ]]; then
        printf '%s\n' export-profile
    elif [[ "$joined" == *" integration "* && "$previous" =~ ^(show|validate|plan|run|status|bindings|bind|unbind)$ ]]; then
        printf '%s\n' integration-route
    elif [[ "$joined" == *" config alias "* && "$previous" =~ ^(set|delete)$ ]]; then
        printf '%s\n' config-alias
    elif [[ "$joined" == *" config permissions profile "* && "$previous" =~ ^(show|set|delete)$ ]]; then
        printf '%s\n' permission-profile
    elif [[ "$joined" == *" plugin "* && "$previous" =~ ^(enable|disable|set|delete|run)$ ]]; then
        printf '%s\n' plugin
    elif [[ "$joined" == *" saved "* && "$previous" =~ ^(show|delete|run)$ ]]; then
        printf '%s\n' saved-report
    elif [[ "$joined" == *" automation run "* && "${COMP_WORDS[COMP_CWORD]}" != -* && ! "$previous" =~ ^--(vault|output|refresh|fields|provider|permissions|limit|offset|color)$ ]]; then
        printf '%s\n' saved-report
    elif [[ "$joined" == *" template "* && "$previous" =~ ^(show|insert|preview)$ ]]; then
        printf '%s\n' template
    elif [[ "$joined" == *" skill "* && "$previous" =~ ^(get|show|commands|run)$ ]]; then
        printf '%s\n' skill
    elif [[ "$joined" =~ \ skill\ run\ ([^\ ]+)\ $ ]]; then
        printf 'skill-command:%s\n' "${BASH_REMATCH[1]}"
    fi
}

__vulcan_dynamic_dispatch() {
    _vulcan "$@"
    local named_context
    named_context="$(__vulcan_named_completion_context)"
    if [[ -n "$named_context" ]]; then
        COMPREPLY=()
        local candidate
        while IFS= read -r candidate; do
            __vulcan_append_completion_candidate "$candidate"
        done < <(__vulcan_dynamic_candidates "$named_context" "${COMP_WORDS[COMP_CWORD]}")
    elif __vulcan_is_tool_run_context; then
        local tool candidate
        tool="$(__vulcan_tool_run_name)"
        if [[ -z "$tool" && "${cur:-${COMP_WORDS[COMP_CWORD]}}" != -* ]]; then
            COMPREPLY=()
            while IFS= read -r candidate; do
                __vulcan_append_completion_candidate "$candidate"
            done < <(__vulcan_dynamic_candidates custom-tool "${COMP_WORDS[COMP_CWORD]}")
        elif [[ -n "$tool" && "${cur:-${COMP_WORDS[COMP_CWORD]}}" == --* ]]; then
            while IFS= read -r candidate; do
                __vulcan_append_completion_candidate "$candidate"
            done < <(__vulcan_dynamic_candidates "custom-tool-flag:$tool" "${COMP_WORDS[COMP_CWORD]}")
        elif [[ -n "$tool" && "${COMP_WORDS[COMP_CWORD - 1]}" == --* ]]; then
            COMPREPLY=()
            local flag="${COMP_WORDS[COMP_CWORD - 1]#--}"
            while IFS= read -r candidate; do
                __vulcan_append_completion_candidate "$candidate"
            done < <(__vulcan_dynamic_candidates "custom-tool-value:$tool:$flag" "${COMP_WORDS[COMP_CWORD]}")
        fi
    elif __vulcan_is_tool_name_context && [[ "${cur:-${COMP_WORDS[COMP_CWORD]}}" != -* ]]; then
        COMPREPLY=()
        local candidate
        while IFS= read -r candidate; do
            __vulcan_append_completion_candidate "$candidate"
        done < <(__vulcan_dynamic_candidates custom-tool "${COMP_WORDS[COMP_CWORD]}")
    fi
}

if [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -ge 4 || "${BASH_VERSINFO[0]}" -gt 4 ]]; then
    complete -F __vulcan_dynamic_dispatch -o nosort -o bashdefault -o default vulcan
else
    complete -F __vulcan_dynamic_dispatch -o bashdefault -o default vulcan
fi

# Override completion for specific subcommand contexts
_vulcan_complete_note_arg() {
    if [[ "${COMP_WORDS[1]}" == "note" || "${COMP_WORDS[1]}" == "links" || "${COMP_WORDS[1]}" == "backlinks" ]]; then
        __vulcan_dynamic_complete note
    fi
}

_vulcan_complete_kanban_arg() {
    if [[ "${COMP_WORDS[1]}" == "kanban" ]]; then
        __vulcan_dynamic_complete kanban-board
    fi
}

_vulcan_complete_bases_arg() {
    if [[ "${COMP_WORDS[1]}" == "bases" ]] && [[ "${COMP_WORDS[2]}" =~ ^(eval|tui|create|view-add|view-delete|view-rename)$ ]]; then
        __vulcan_dynamic_complete bases-file
    fi
}
