
# Dynamic completions — generated by vulcan completions fish
function __fish_vulcan_expand_leading_tilde
    set -l value $argv[1]
    if test "$value" = "~"
        if set -q HOME
            printf '%s\n' "$HOME"
            return
        end
    end
    if string match -q -- '~/*' "$value"
        if set -q HOME
            printf '%s/%s\n' "$HOME" (string sub -s 3 -- "$value")
            return
        end
    end
    printf '%s\n' "$value"
end

function __fish_vulcan_completion_prefix_args
    set -l words (commandline -opc)
    set -l args
    set -l i 2
    while test $i -le (count $words)
        set -l word $words[$i]
        switch $word
            case '--vault' '--output' '--refresh' '--fields' '--provider' '--permissions' '--limit' '--offset' '--color'
                set args $args $word
                set -l next (math $i + 1)
                if test $next -le (count $words)
                    if test "$word" = "--vault"
                        set args $args (__fish_vulcan_expand_leading_tilde $words[$next])
                    else
                        set args $args $words[$next]
                    end
                end
                set i (math $i + 2)
            case '--vault=*' '--output=*' '--refresh=*' '--fields=*' '--provider=*' '--permissions=*' '--limit=*' '--offset=*' '--color=*'
                if string match -q -- '--vault=*' "$word"
                    set -l value (string replace -r '^--vault=' '' -- "$word")
                    set args $args --vault=(__fish_vulcan_expand_leading_tilde $value)
                else
                    set args $args $word
                end
                set i (math $i + 1)
            case '--verbose' '--quiet' '-q' '--no-header'
                set args $args $word
                set i (math $i + 1)
            case '--'
                break
            case '-*'
                break
            case '*'
                break
        end
    end
    for arg in $args
        printf '%s\n' $arg
    end
end

function __fish_vulcan_seen_flag
    set -l target $argv[1]
    contains -- $target (commandline -opc)
end

function __fish_vulcan_dynamic_complete_note
    set -l args (__fish_vulcan_completion_prefix_args)
    set -l prefix (commandline -ct)
    set -l cmd "__VULCAN_CMD__"
    $cmd $args complete note "$prefix" 2>/dev/null
end

function __fish_vulcan_dynamic_complete_kanban_board
    set -l args (__fish_vulcan_completion_prefix_args)
    set -l prefix (commandline -ct)
    set -l cmd "__VULCAN_CMD__"
    $cmd $args complete kanban-board "$prefix" 2>/dev/null
end

function __fish_vulcan_dynamic_complete_bases_file
    set -l args (__fish_vulcan_completion_prefix_args)
    set -l prefix (commandline -ct)
    set -l cmd "__VULCAN_CMD__"
    $cmd $args complete bases-file "$prefix" 2>/dev/null
end

function __fish_vulcan_dynamic_complete_daily_date
    set -l args (__fish_vulcan_completion_prefix_args)
    set -l prefix (commandline -ct)
    set -l cmd "__VULCAN_CMD__"
    $cmd $args complete daily-date "$prefix" 2>/dev/null
end

function __fish_vulcan_dynamic_complete_script
    set -l args (__fish_vulcan_completion_prefix_args)
    set -l prefix (commandline -ct)
    set -l cmd "__VULCAN_CMD__"
    $cmd $args complete script "$prefix" 2>/dev/null
end

function __fish_vulcan_dynamic_complete_task_view
    set -l args (__fish_vulcan_completion_prefix_args)
    set -l prefix (commandline -ct)
    set -l cmd "__VULCAN_CMD__"
    $cmd $args complete task-view "$prefix" 2>/dev/null
end

function __fish_vulcan_dynamic_complete_custom_tool
    set -l args (__fish_vulcan_completion_prefix_args)
    set -l prefix (commandline -ct)
    set -l cmd "__VULCAN_CMD__"
    $cmd $args complete custom-tool "$prefix" 2>/dev/null
end

function __fish_vulcan_tool_run_name
    set -l words (commandline -opc)
    set -l i 1
    while test $i -le (count $words)
        if test "$words[$i]" = "tool"
            set -l next (math $i + 1)
            if test $next -le (count $words); and test "$words[$next]" = "run"
                set -l j (math $i + 2)
                while test $j -le (count $words)
                    set -l word $words[$j]
                    switch $word
                        case '--input-json' '--input-file'
                            set j (math $j + 2)
                        case '--*'
                            set j (math $j + 1)
                        case '*'
                            printf '%s\n' "$word"
                            return
                    end
                end
            end
        end
        set i (math $i + 1)
    end
end

function __fish_vulcan_dynamic_complete_custom_tool_flag
    set -l tool (__fish_vulcan_tool_run_name)
    if test -z "$tool"
        return
    end
    set -l args (__fish_vulcan_completion_prefix_args)
    set -l prefix (commandline -ct)
    set -l cmd "__VULCAN_CMD__"
    $cmd $args complete custom-tool-flag:$tool "$prefix" 2>/dev/null
end

function __fish_vulcan_dynamic_complete_custom_tool_value
    set -l tool (__fish_vulcan_tool_run_name)
    if test -z "$tool"
        return
    end
    set -l words (commandline -opc)
    set -l previous $words[-1]
    if not string match -q -- '--*' "$previous"
        return
    end
    set -l flag (string replace -r '^--' '' -- "$previous")
    set -l args (__fish_vulcan_completion_prefix_args)
    set -l prefix (commandline -ct)
    set -l cmd "__VULCAN_CMD__"
    $cmd $args complete custom-tool-value:$tool:$flag "$prefix" 2>/dev/null
end

function __fish_vulcan_complete_vault_path_arg
    set -l args (__fish_vulcan_completion_prefix_args)
    set -l prefix (commandline -ct)
    set -l cmd "__VULCAN_CMD__"
    $cmd $args complete vault-path "$prefix" 2>/dev/null
end

# Note names for note subcommands
complete -c vulcan -n "__fish_vulcan_using_subcommand note; and __fish_seen_subcommand_from get set append update unset patch delete rename info history links backlinks diff doctor" -f -a "(__fish_vulcan_dynamic_complete_note)" -d "Note"
complete -c vulcan -n "__fish_vulcan_using_subcommand links" -f -a "(__fish_vulcan_dynamic_complete_note)" -d "Note"
complete -c vulcan -n "__fish_vulcan_using_subcommand backlinks" -f -a "(__fish_vulcan_dynamic_complete_note)" -d "Note"
complete -c vulcan -n "__fish_vulcan_using_subcommand open" -f -a "(__fish_vulcan_dynamic_complete_note)" -d "Note"
complete -c vulcan -n "__fish_vulcan_using_subcommand edit; and not __fish_vulcan_seen_flag --new" -f -a "(__fish_vulcan_dynamic_complete_note)" -d "Note"
complete -c vulcan -n "__fish_vulcan_using_subcommand link-mentions" -f -a "(__fish_vulcan_dynamic_complete_note)" -d "Note"
complete -c vulcan -n "__fish_vulcan_using_subcommand suggest; and __fish_seen_subcommand_from mentions" -f -a "(__fish_vulcan_dynamic_complete_note)" -d "Note"
complete -c vulcan -n "__fish_vulcan_using_subcommand dataview; and __fish_seen_subcommand_from inline eval" -f -a "(__fish_vulcan_dynamic_complete_note)" -d "Note"

# Kanban board names
complete -c vulcan -n "__fish_vulcan_using_subcommand kanban; and __fish_seen_subcommand_from show add move archive" -f -a "(__fish_vulcan_dynamic_complete_kanban_board)" -d "Board"

# Bases .base file paths
complete -c vulcan -n "__fish_vulcan_using_subcommand bases; and __fish_seen_subcommand_from eval tui create view-add view-delete view-rename" -f -a "(__fish_vulcan_dynamic_complete_bases_file)" -d "Bases file"

# Daily date patterns
complete -c vulcan -n "__fish_vulcan_using_subcommand daily; and __fish_seen_subcommand_from show" -f -a "(__fish_vulcan_dynamic_complete_daily_date)" -d "Date"

# Script names for vulcan run
complete -c vulcan -n "__fish_vulcan_using_subcommand run" -f -a "(__fish_vulcan_dynamic_complete_script)" -d "Script"

# Skill-backed custom tools and declared CLI flags
complete -c vulcan -n "__fish_vulcan_using_subcommand tool; and __fish_seen_subcommand_from show help test compat types" -f -a "(__fish_vulcan_dynamic_complete_custom_tool)" -d "Tool"
complete -c vulcan -n "__fish_vulcan_using_subcommand tool; and __fish_seen_subcommand_from run" -f -a "(__fish_vulcan_dynamic_complete_custom_tool)" -d "Tool"
complete -c vulcan -n "__fish_vulcan_using_subcommand tool; and __fish_seen_subcommand_from run" -f -a "(__fish_vulcan_dynamic_complete_custom_tool_flag)" -d "Tool flag"
complete -c vulcan -n "__fish_vulcan_using_subcommand tool; and __fish_seen_subcommand_from run" -f -a "(__fish_vulcan_dynamic_complete_custom_tool_value)" -d "Tool value"

# Vault-relative path arguments
complete -c vulcan -n "__fish_vulcan_using_subcommand note; and __fish_seen_subcommand_from create" -f -a "(__fish_vulcan_complete_vault_path_arg)" -d "Path"
complete -c vulcan -n "__fish_vulcan_using_subcommand edit; and __fish_vulcan_seen_flag --new" -f -a "(__fish_vulcan_complete_vault_path_arg)" -d "Path"
complete -c vulcan -n "__fish_vulcan_using_subcommand move" -f -a "(__fish_vulcan_complete_vault_path_arg)" -d "Path"
complete -c vulcan -n "__fish_vulcan_using_subcommand git; and __fish_seen_subcommand_from diff blame" -f -a "(__fish_vulcan_complete_vault_path_arg)" -d "Path"

# Task view names for tasks view show <name>
# Condition: view has been seen AND show has been seen (nested sub-subcommand context).
complete -c vulcan -n "__fish_vulcan_using_subcommand tasks; and __fish_seen_subcommand_from view; and __fish_seen_subcommand_from show" -f -a "(__fish_vulcan_dynamic_complete_task_view)" -d "View"
