
# Dynamic completions patch — generated by vulcan completions zsh
_vulcan_completion_prefix_args() {
    local -a args
    local i=2
    local word
    while (( i <= ${#words} )); do
        word="${words[i]}"
        case "$word" in
            --vault|--output|--refresh|--fields|--provider|--permissions|--limit|--offset|--color)
                args+=("$word")
                if (( i + 1 <= ${#words} )); then
                    args+=("${words[i+1]}")
                fi
                (( i += 2 ))
                ;;
            --vault=*|--output=*|--refresh=*|--fields=*|--provider=*|--permissions=*|--limit=*|--offset=*|--color=*)
                args+=("$word")
                (( i += 1 ))
                ;;
            --verbose|--quiet|-q|--no-header)
                args+=("$word")
                (( i += 1 ))
                ;;
            --)
                break
                ;;
            -*)
                break
                ;;
            *)
                break
                ;;
        esac
    done
    reply=("${args[@]}")
}

_vulcan_complete_note() {
    local cmd="__VULCAN_CMD__"
    local -a args notes
    _vulcan_completion_prefix_args
    args=("${reply[@]}")
    notes=(${(f)"$("$cmd" "${args[@]}" complete note "${words[CURRENT]}" 2>/dev/null)"})
    _describe 'note' notes
}

_vulcan_complete_kanban_board() {
    local cmd="__VULCAN_CMD__"
    local -a args boards
    _vulcan_completion_prefix_args
    args=("${reply[@]}")
    boards=(${(f)"$("$cmd" "${args[@]}" complete kanban-board "${words[CURRENT]}" 2>/dev/null)"})
    _describe 'board' boards
}

_vulcan_complete_bases_file() {
    local cmd="__VULCAN_CMD__"
    local -a args files
    _vulcan_completion_prefix_args
    args=("${reply[@]}")
    files=(${(f)"$("$cmd" "${args[@]}" complete bases-file "${words[CURRENT]}" 2>/dev/null)"})
    _describe 'bases file' files
}

_vulcan_complete_daily_date() {
    local cmd="__VULCAN_CMD__"
    local -a args dates
    _vulcan_completion_prefix_args
    args=("${reply[@]}")
    dates=(${(f)"$("$cmd" "${args[@]}" complete daily-date "${words[CURRENT]}" 2>/dev/null)"})
    _describe 'date' dates
}

_vulcan_complete_script() {
    local cmd="__VULCAN_CMD__"
    local -a args scripts
    _vulcan_completion_prefix_args
    args=("${reply[@]}")
    scripts=(${(f)"$("$cmd" "${args[@]}" complete script "${words[CURRENT]}" 2>/dev/null)"})
    _describe 'script' scripts
}

_vulcan_complete_task_view() {
    local cmd="__VULCAN_CMD__"
    local -a args views
    _vulcan_completion_prefix_args
    args=("${reply[@]}")
    views=(${(f)"$("$cmd" "${args[@]}" complete task-view "${words[CURRENT]}" 2>/dev/null)"})
    _describe 'view' views
}

_vulcan_complete_custom_tool() {
    local cmd="__VULCAN_CMD__"
    local -a args tools
    _vulcan_completion_prefix_args
    args=("${reply[@]}")
    tools=(${(f)"$("$cmd" "${args[@]}" complete custom-tool "${words[CURRENT]}" 2>/dev/null)"})
    _describe 'tool' tools
}

_vulcan_tool_run_name() {
    local i j word
    for (( i = 1; i < CURRENT; i++ )); do
        if [[ "${words[i]}" == "tool" && "${words[i + 1]}" == "run" ]]; then
            j=$((i + 2))
            while (( j < CURRENT )); do
                word="${words[j]}"
                case "$word" in
                    --input-json|--input-file)
                        (( j += 2 ))
                        ;;
                    --*)
                        (( j += 1 ))
                        ;;
                    *)
                        print -r -- "$word"
                        return
                        ;;
                esac
            done
        fi
    done
}

_vulcan_complete_custom_tool_flag() {
    local cmd="__VULCAN_CMD__"
    local -a args flags
    local tool="$(_vulcan_tool_run_name)"
    [[ -z "$tool" ]] && return
    _vulcan_completion_prefix_args
    args=("${reply[@]}")
    flags=(${(f)"$("$cmd" "${args[@]}" complete custom-tool-flag:$tool "${words[CURRENT]}" 2>/dev/null)"})
    _describe 'tool flag' flags
}

_vulcan_complete_custom_tool_value() {
    local cmd="__VULCAN_CMD__"
    local -a args values
    local tool="$(_vulcan_tool_run_name)"
    [[ -z "$tool" ]] && return
    local previous="${words[CURRENT - 1]}"
    [[ "$previous" != --* ]] && return
    local flag="${previous#--}"
    _vulcan_completion_prefix_args
    args=("${reply[@]}")
    values=(${(f)"$("$cmd" "${args[@]}" complete custom-tool-value:$tool:$flag "${words[CURRENT]}" 2>/dev/null)"})
    _describe 'tool value' values
}

_vulcan_is_tool_run_context() {
    local i
    for (( i = 1; i < CURRENT; i++ )); do
        if [[ "${words[i]}" == "tool" && "${words[i + 1]}" == "run" ]]; then
            return 0
        fi
    done
    return 1
}

_vulcan_is_tool_name_context() {
    local i command
    for (( i = 1; i < CURRENT; i++ )); do
        if [[ "${words[i]}" == "tool" ]]; then
            command="${words[i + 1]}"
            if [[ "$command" =~ ^(show|help|test|compat|types)$ ]]; then
                return 0
            fi
        fi
    done
    return 1
}

_vulcan_custom_tool_candidates() {
    local context="$1"
    local prefix="$2"
    local cmd="__VULCAN_CMD__"
    local -a args candidates
    _vulcan_completion_prefix_args
    args=("${reply[@]}")
    candidates=(${(f)"$("$cmd" "${args[@]}" complete "$context" "$prefix" 2>/dev/null)"})
    (( ${#candidates} )) && compadd -a candidates
}

_vulcan_named_completion_context() {
    local previous="${words[CURRENT - 1]}"
    local joined=" ${(j: :)words[1,CURRENT-1]} "
    case "$previous" in
        --permissions|--clone|--permission-profile)
            print -r -- permission-profile
            return
            ;;
        --site-profile)
            print -r -- site-profile
            return
            ;;
        --profile)
            if [[ "$joined" == *" export outline-zip "* ]]; then
                print -r -- outline-profile
            elif [[ "$joined" == *" site "* ]]; then
                print -r -- site-profile
            elif [[ "$joined" == *" tool "* ]]; then
                print -r -- permission-profile
            fi
            return
            ;;
    esac

    if [[ "$previous" == outline && "$joined" =~ ' (publish|pull) outline $' ]]; then
        print -r -- outline-profile
    elif [[ "$joined" == *" outline collections "* && "$previous" =~ '^(list|show|create|update|archive|restore|bind)$' ]]; then
        print -r -- outline-profile
    elif [[ "$joined" == *" export profile rule "* && "$previous" =~ '^(list|add|update|delete|move)$' ]]; then
        print -r -- export-profile
    elif [[ "$joined" == *" export profile "* && "$previous" =~ '^(run|serve|show|set|delete)$' ]]; then
        print -r -- export-profile
    elif [[ "$joined" == *" integration "* && "$previous" =~ '^(show|validate|plan|run|status|bindings|bind|unbind)$' ]]; then
        print -r -- integration-route
    elif [[ "$joined" == *" config alias "* && "$previous" =~ '^(set|delete)$' ]]; then
        print -r -- config-alias
    elif [[ "$joined" == *" config permissions profile "* && "$previous" =~ '^(show|set|delete)$' ]]; then
        print -r -- permission-profile
    elif [[ "$joined" == *" plugin "* && "$previous" =~ '^(enable|disable|set|delete|run)$' ]]; then
        print -r -- plugin
    elif [[ "$joined" == *" saved "* && "$previous" =~ '^(show|delete|run)$' ]]; then
        print -r -- saved-report
    elif [[ "$joined" == *" automation run "* && "${words[CURRENT]}" != -* && ! "$previous" =~ '^--(vault|output|refresh|fields|provider|permissions|limit|offset|color)$' ]]; then
        print -r -- saved-report
    elif [[ "$joined" == *" template "* && "$previous" =~ '^(show|insert|preview)$' ]]; then
        print -r -- template
    elif [[ "$joined" == *" skill "* && "$previous" =~ '^(get|show|commands|run)$' ]]; then
        print -r -- skill
    elif [[ "$joined" =~ ' skill run ([^ ]+) $' ]]; then
        print -r -- "skill-command:${match[1]}"
    fi
}

if functions -c _vulcan _vulcan_static 2>/dev/null; then
    _vulcan() {
        _vulcan_static "$@"
        local named_context="$(_vulcan_named_completion_context)"
        if [[ -n "$named_context" ]]; then
            _vulcan_custom_tool_candidates "$named_context" "${words[CURRENT]}"
        elif _vulcan_is_tool_run_context; then
            local tool="$(_vulcan_tool_run_name)"
            if [[ -z "$tool" && "${words[CURRENT]}" != -* ]]; then
                _vulcan_custom_tool_candidates custom-tool "${words[CURRENT]}"
            elif [[ -n "$tool" && "${words[CURRENT]}" == --* ]]; then
                _vulcan_custom_tool_candidates "custom-tool-flag:$tool" "${words[CURRENT]}"
            elif [[ -n "$tool" && "${words[CURRENT - 1]}" == --* ]]; then
                local flag="${words[CURRENT - 1]#--}"
                _vulcan_custom_tool_candidates "custom-tool-value:$tool:$flag" "${words[CURRENT]}"
            fi
        elif _vulcan_is_tool_name_context && [[ "${words[CURRENT]}" != -* ]]; then
            _vulcan_custom_tool_candidates custom-tool "${words[CURRENT]}"
        fi
    }
    compdef _vulcan vulcan
fi
